services:
  - type: web
    name: my-fastapi-app
    env: python
    repo: https://github.com/yourusername/your-repo
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: postgresql://topotik_test_db_user:tUNRiVqHiwDGIz2SyqhGcJQYIezYJZKz@dpg-cv4btiggph6c738ub4a0-a.frankfurt-postgres.render.com/topotik_test_db
